import SearchBox from "../components/SearchBox";
import { PrismaClient } from "@prisma/client";
import { Metadata } from "next";
import SearchHeader from "./components/SearchHeader";
import SearchSidebar from "./components/SearchSidebar";

export const metadata: Metadata = {
  title: "Search",
  description: "Generated by create next app",
  keywords: ["aryan", "page"],
};

const prisma = new PrismaClient();

interface searchParams {
  title?: string;
  brand?: string;
  category?: string;
}

const fetchRestaurant = (searchParams: searchParams) => {
  const where: any = {};

  if (searchParams.title) {
    const location = {
      name: {
        equals: searchParams.title.toLocaleLowerCase(),
      },
    };
    where.location = location;
  }

  if (searchParams.brand) {
    const brand = {
      name: {
        equals: searchParams.brand.toLocaleLowerCase(),
      },
    };
    where.brand = brand;
  }

  if (searchParams.category) {
    const category = {
      equals: searchParams.category,
    };
    where.category = category;
  }

  const select = {
    id: true,
    name: true,
    main_image: true,
    category: true,
    location: true,
    brand: true,
    slug: true,
    reviews: true,
  };

  return prisma.products.findMany({
    where,
    select,
  });
};

const fetchProducts = () => {
  return prisma.products.findMany();
};

const fetchbrands = () => {
  return prisma.products.deleteMany() ;
};

export default async function page({
  searchParams,
}: {
  searchParams: searchParams;
}) {
  const products = await fetchProducts(searchParams);
  const category = await fetchProducts();
  const brands = await fetchbrands();

  return (
    <>
      <SearchHeader />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SearchSidebar
          products={products}
          brands={brands}
          searchParams={searchParams}
        />
        <div className="w-5/6">
          {products.length ? (
            products.map((product) => (
              <SearchBox product={product} />
            ))
          ) : (
            <p>Sorry no product found !!</p>
          )}
        </div>
      </div>
    </>
  );
}
